package domain

import "time"

// UserStats holds aggregated cost and usage metrics for a single user
// within a project. Derived from the user_agg ClickHouse materialized view.
//
// user_id is an opaque identifier set by the caller (e.g. UUID or internal
// customer ID). It is never auto-generated by AgentPulse.
type UserStats struct {
	UserID    string
	ProjectID string

	RunCount     uint64
	TotalCostUSD float64
	TotalTokens  int64
	InputTokens  int64
	OutputTokens int64
	ErrorCount   uint64

	FirstSeenAt time.Time
	LastSeenAt  time.Time

	// CostPercent is the percentage of total project cost attributed to this
	// user. Computed by the API handler, not stored in ClickHouse.
	CostPercent float64
}
